{% set name = "optimix" %}
{% set version = "1.2.18" %}
{% set sha256 = "c79dec033a25b4378d8098deabe90e85e81f6d92c7c01d17721903815d86017c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - numpy
    - scipy
    - ndarray-listener
    - brent-search
    - tqdm

test:
  requires:
    - pytest
    - pytest-pep8
  imports:
    - optimix
  commands:
    - python -c "import sys; import optimix; sys.exit(optimix.test())"

about:
  home: https://github.com/limix/optimix
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Abstract function optimisation'
  doc_url: https://optimix.readthedocs.io/
  dev_url: https://github.com/limix/optimix

extra:
  recipe-maintainers:
    - Horta
