{% set name = "optimix" %}
{% set version = "2.0.0" %}
{% set sha256 = "3db13479312e395042d1b0c0eea2544ce332a67676bf0654aaf3254512061e8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools >=36.7.2
    - pytest-runner
    - pypandoc
    - wheel
    - pip
  run:
    - python
    - numpy
    - scipy
    - ndarray-listener >=1.1.1
    - brent-search >=1.0.32
    - tqdm

test:
  requires:
    - pytest
    - pytest-pep8
  imports:
    - optimix
  commands:
    - python -c "import sys; import optimix; sys.exit(optimix.test())"

about:
  home: https://github.com/limix/optimix
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Abstract function optimisation'
  doc_url: https://optimix.readthedocs.io/
  dev_url: https://github.com/limix/optimix

extra:
  recipe-maintainers:
    - Horta
