{% set name = "optimix" %}
{% set version = "1.1.5" %}
{% set sha256 = "1fa0402db581a7c48da19e73604f6a0dab51e5fddb034fdf3b43d91609b020ca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - numpy
    - scipy
    - ndarray-listener
    - brent-search

test:
  requires:
    - pytest
  imports:
    - optimix
  commands:
    - python -c "import sys; import optimix; sys.exit(optimix.test())"

about:
  home: https://github.com/glimix/optimix
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Abstract function optimisation'
  doc_url: http://optimix.readthedocs.io/
  dev_url: https://github.com/glimix/optimix

extra:
  recipe-maintainers:
    - Horta
