travis:
  secure:
    BINSTAR_TOKEN: pyY/DOXGm7uaM956HKPN8YUvWOMRZwRD7ztwXxifV/rJD6GlSpipwCR1EB9V+1SqCVTgci8Y8FDVYJPAySNRsGQrX3Ba7/WNWDT6bWt0EGFSC+2i0aY/vpaK/GfqQ/ZnKA08NUk6n+CpJKydQAmYT40acgSE9YSecak2oEdmcQZivt1DoMI2GE1CxKefyTTp6nqtW9sBHBf3H0OjL4kYmiYj0/Nkn/J62cTESKBo9sc+/OB4xUmfrt3YYcdczLQL0pmP1VTkDI5MIAxevCwUCdzSe5Ci+xF5MRqwqneHt1gXwPFHKgXgS9KHlAg5E5DcjBAVcJvvmi/sqe6l1iDdCG3vk9LpG9nzbF4EExKt09/YpvcJnYxhtqt+7qF/cbS0ckf1S58gxJnpParJfl21g3pf+iP+A8ZFthsBKGhjUrqtMk78mio5gEPW4VgOmSAd/3p6LkPnVmUasY3cN2kSyf1GHTZt7bw1Tg95+eNn6YABgWpzJqxctNE8c7OB3mn4/W6dlDqV09j6RXyX4Ems+yIpYKlBAIUawtAcHdmzaj5OB2KRMBAqszqiunlSVR/ko7EsVOrxj7jSeRea+lQmSMvHYNK/VqSrWIrdF+dvGoN/GnVrbo9g21/25PWsM9z5XmfHbzhwmKVpeWAE4zfBokg38nxx5Jc/t2r6XslfaJI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
