travis:
  secure:
    BINSTAR_TOKEN: IOoTBZ2HfWmLMsUnfqwlJ65RgeL8bL7MuEp3EMcHDl/zjYa19BQmpVM+UrYQBcfbguTaHT5mjhIFtxJKNnVm2kUMi+zm00XqBkyk5U6UcUzOQeoBfA024IGFLzjNDhuFwX6MAssHWGNV3g53nvqRD3rgPUPxXaDDbj15uGyON0zNhhS+stXjVHPejApe34/0xOby/AMllNj2AMSHBjvloZWVw7Lf2x0MUUCn5u2qKYhTS5VbzgIp9z+tU+uMlrE7k1oI2NgXjgp2zWYKpx8ti58sJBGrOOEiTEOcfkNo/6CB7yvCLj+uZfb8JTK9F4kkVBW7snA4VIt5aTgFEhIixp8QeBGDUkIiFRKB4qDHqEfI4d20PswaIDo6aHpirkA1P6jdphBBfPltGPdO5tyTg7pOXCF1GUnBD+7+jF7++4N7dJhBvfJ8nSTrPjBDibKkIWN3e82qhuntpAvV76XCUhZREYsb5hpjJakpdMraXyLUsn8eyWoiaT2izyMNhevt2Ij8doQIHtUfsvUw9pdDW22XBMTIQ80zXPMbf1SNawpFyP9ICzj2Dd7leYItuyCzqzAWSLNCFYjgVcabzg+7pyycBk2DmVDShBDmfKeCLuTyhH/2QMiR/6b/QAvrMXvmFw3t1HSa0WH4cg3dufKs1vUxum7XVv5S93TxkN3eYKU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
